### ISSUE TITLE
Bug: Found a mistake in a command in the CONTRIBUTING.md File

### ISSUE THREAD

**Issue by heyaadarsh** [shikhar13012001/css-awesomeness#10]
### What happened?

I was reading instructions to contribute on the [CONTRIBUTING.md](https://github.com/shikhar13012001/css-awesomeness/blob/main/CONTRIBUTING.md) page (Page that you mentioned in the Readme file) and I found a mistake in Git command in "Step 6". 
For checking out the new branch, you have written the command "git **brach** -b <branch_name>" but there is a minor mistake in the spelling of "branch", which can cause many difficulties for newbies. Please assign me to correct that small mistake.

Thanks for making this awesome repo!

### How can we reproduce this bug?

We just have to correct the spelling of "branch".

### Urgency (Optional)

High priority

**Comment by shikhar13012001** [comment]
Thanks for pointing it out @heyaadarsh , Can you make the PR for this ? thanks again! sorry for late reply.

**Comment by heyaadarsh** [comment]
> Thanks for pointing it out @heyaadarsh , Can you make the PR for this ? thanks again! sorry for late reply.

@shikhar13012001 Thank you so much for assigning me! I fixed that mistake and made a PR also, please check it out and merge it into your awesome repo! 
Thanks Again!
